### ISSUE TITLE
ImportError: No module named distance

### ISSUE THREAD

**Issue by URBabylab** [BergelsonLab/wordmerge2#17]
Azalea:wordmerge2 bergelsonlab$ python wordmerge2.py /Volumes/pn-opus/Seedlings/Scripts_and_Apps/wordmerge/latest/video_merge_12-13-16/batch_video_output/23_10_coderSD_video_checkSM_wordmerged.csv /Volumes/pn-opus/Seedlings/Working_Files/23_10/video/23_10_coderND.csv 23_10_wm.csv
Traceback (most recent call last):
  File "wordmerge2.py", line 4, in <module>
    import codecheck
  File "/Users/bergelsonlab/Desktop/GitHub/SeedlingsBabylab/codecheck/codecheck/__init__.py", line 16, in <module>
    from spellcheck import spellcheck
  File "/Users/bergelsonlab/Desktop/GitHub/SeedlingsBabylab/codecheck/codecheck/spellcheck.py", line 4, in <module>
    import distance
ImportError: No module named distance
![screen shot 2017-12-08 at 1 25 18 pm](https://user-images.githubusercontent.com/11462259/33779585-7c7dc2ee-dc1b-11e7-8f6f-92e7f37706d2.png)

**Comment by andreiamatuni** [comment]
run this command:

```bash
$ pip install distance
```
